version: '3'

services:
  app:
    build: .
    command: yarn dev
    ports:
      - '3000:3000'
    volumes:
      - .:/src

  db:
    container_name: 'database-node'
    image: mysql:5.7.31
    restart: always
    ports:
      - '3308:3306'
    command: --init-file /data/application/init.sql
    volumes:
      - ./data/application/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: jhmi248824
      MYSQL_DATABASE: prospects
      MYSQL_USER: root
      MYSQL_PASSWORD: jhmi248824
      TZ: America/Sao_Paulo
